name: my_project
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  camera: ^0.10.5+9
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  permission_handler: ^11.0.1
  http: ^1.2.0
  url_launcher: ^6.2.4
  uuid: ^4.3.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.4.0
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/users/
    - assets/images/icons/
    - assets/images/navbar/
    - .env
